services:
  # Backend API Service
  - type: web
    name: tailortalk-backend
    runtime: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.18"
      - key: ENVIRONMENT
        value: "production"
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CALENDAR_CREDENTIALS
        sync: false
      - key: USE_SERVICE_ACCOUNT
        value: "true"
      - key: CALENDAR_ID
        sync: false
      - key: API_TOKEN
        generateValue: true # Automatically generate a secure API token 